// stdafx.h : 자주 사용하지만 자주 변경되지는 않는
// 표준 시스템 포함 파일 및 프로젝트 관련 포함 파일이
// 들어 있는 포함 파일입니다.
//

#pragma once

#include "targetver.h"

#include <atltime.h>

#include <stdio.h>
#include <tchar.h>
#include <WinSock2.h>

// Turn off warnings generated by long std templates
// This warns about truncation to 255 characters in debug/browse info
#   pragma warning(disable:4786)

// disable: "conversion from 'double' to 'float', possible loss of data
#   pragma warning(disable:4244)

// disable: "truncation from 'double' to 'float'
#   pragma warning(disable:4305)

// disable: "<type> needs to have dll-interface to be used by clients'
// Happens on STL member variables which are not public therefore is ok
#   pragma warning(disable:4251)

// disable: "non dll-interface class used as base for dll-interface class"
// Happens when deriving from Singleton because bug in compiler ignores
// template export
#   pragma warning(disable:4275)

// disable: "C++ Exception Specification ignored"
// This is because MSVC 6 did not implement all the C++ exception 
// specifications in the ANSI C++ draft.
#   pragma warning(disable:4290)

// disable: "no suitable definition provided for explicit template 
// instantiation request" Occurs in VC7 for no justifiable reason on all 
// #includes of Singleton
#   pragma warning(disable:4661)

// for <strsafe.h>
#	pragma warning(disable:4995)

#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <cstring>
#include <cstdarg>
#include <cmath>
#include <atldbcli.h>

#include <vector>
#include <map>
#include <string>
#include <set>
#include <list>
#include <deque>

#include <algorithm>
#include <functional>
#include <random>
#include <utility>
#include <limits>
#include <strsafe.h>

//******* 추가 전처리기 *******//
#if defined ( SRC_TH )
	#define CUSTOM_COSTUME
	#define HERO_POSSIBLE_CHECK //용병 사용제한 
#endif

#if defined ( SRC_ID )
#define DIVIDE_PET
#endif

#if defined ( SRC_SEA )
#define SRC_SEA
#endif

#if defined ( SRC_OVERSEAS )
	#define ROTATION_MISSION //일일,주간,월간 미션 로테이션
	#define DEV_K_NAME "DeveloperK"
#endif

#ifdef LOCAL_DBG
//	#define CUSTOM_COSTUME
	//#define DIVIDE_PET
	#define SRC_NA
#endif

//*****************************//

//#define NPROTECT
//#define NPROTECT_CSAUTH3
//#ifndef NPROTECT
//	#define XTRAP
//#endif

// TODO: 프로그램에 필요한 추가 헤더는 여기에서 참조합니다.
#include "../include/common.h"

#include <iostream>
using namespace std;

#include "../iocpSocketDLL/iocpSocketDLL.h"


#include "../include/Log.h"
#include "../FrameTimerDLL/FrameTimerDll.h"
#include "Util/Singleton.h"

#include "../ioINILoader/ioINILoader.h"

#include "Util/ioHashString.h"
#include "Define.h"
#include "ProtocolHelper.h"
#include "ioProcessChecker.h"
#include "ioPacketChecker.h"
#include "ioCriticalError.h"
#include "Util/ioStringConverter.h"
#include "./NodeInfo/ioINIManager.h"
#include "Util/ioEncrypted.h"
#include "Network/SP2Packet.h"
#include "Network/GameSvrUDPModule.h"
#include "Network/GameSvrUDPNode.h"
#include "Network/ioBroadCastRelayModule.h"

#include "DataHeaders/DataEnum.h"

#include "NodeInfo/User.h"
#include "NodeInfo/ModeHelp.h"

#include "NodeInfo/ModeCreator.h"

extern CLog ReportLOG;
extern CLog LOG;

extern void Trace( const char *format, ... );
extern void Debug( const char *format, ... );
extern void Information( const char *format, ... ) ;
extern void Debug();
