#ifndef ___PROTOCOL_H__
#define ___PROTOCOL_H__

// Scheduler
#define ITPK_ACCEPT_SESSION					0x1001
#define ITPK_SENDBUFFER_FLUSH_PROCESS		0x1007

// SessionClose
#define	CFTPK_CLOSE_SESSION			0x3000

// CLIENT SEND TO FILESERVER PACKET 0x12001 ~ 0x13000
#define CFTPK_FILE_WRITE            0x12001
#define CFTPK_ALL_FILE_WRITE		0x12002

// FILESERVER SEND TO CLIENT PACKET 0x13001 ~ 0x14000
#define SFTPK_FILE_WRITE            0x13001
#define SFTPK_ALL_FILE_WRITE        0x13002

// CFTPK_FILE_WRITE, CFTPK_ALL_FILE_WRITE
#define FILE_WRITE_START   1
#define FILE_WRITE_PROCESS 2
#define FILE_WRITE_END     3
#define FILE_WRITE_PROCESS_ERROR 4

// SFTPK_FILE_WRITE, SFTPK_ALL_FILE_WRITE
#define FILE_WRITE_SUCCESS         1
#define FILE_WRITE_ERROR_FILE_NAME 2   
#define FILE_WRITE_EXIST_FILE      3
#define FILE_WRITE_ERROR_CREATE_FILE 4
#define FILE_WRITE_ERROR_WRITE_FILE  5
#define FILE_WRITE_ERROR_FILE_CRC    6
#define FILE_WRITE_ERROR_MOVE_FILE   7
#define FILE_WRITE_ERROR_WRONG_FILE  8
#define FILE_WRITE_START_OK          9
#define FILE_WRITE_EXEPTION			10
#endif
