#pragma once

enum WemadeLogTypes
{
	WE_LOG_BEGIN = 0,

	WE_LOG_CONCURRENT = 101,
	WE_LOG_DATA_PCROOM = 201,

	WE_LOG_BUY_ITEM_CLASS = 301,
	WE_LOG_BUY_ITEM_DECORATION = 302,
	WE_LOG_BUY_ITEM_EQUIP = 303,
	WE_LOG_DATA_LEAGUE_PRESENT = 304,
	WE_LOG_DATA_PIECE_OBTAIN = 305,
	WE_LOG_DATA_PIECE_MIX = 306,
	WE_LOG_DATA_PIECE_DIVIDE = 307,
	WE_LOG_BUY_ITEM_GOLD = 308,
	WE_LOG_DATA_MEDAL = 309,
	WE_LOG_DATA_MEDAL_EXTEND = 310,
	WE_LOG_DATA_TRADE = 311,
	WE_LOG_DATA_LOCALINFO = 312,
	WE_LOG_DATA_TUTORIAL = 313,
	WE_LOG_USE_ITEM = 314,

	WE_LOG_BUY_ITEM_SPECIAL = 401,
	WE_LOG_DATA_CLOVER = 402,
	WE_LOG_DATA_PLAY = 403,
	WE_LOG_DATA_TIME = 404,

	WE_LOG_DATA_CHARACTER = 501,
	WE_LOG_DATA_PESO = 502,
	WE_LOG_DATA_QUEST = 503,
	WE_LOG_PRESENT = 504,

	WE_LOG_END = 1000
};
