#ifndef ___PROTOCOL_H__
#define ___PROTOCOL_H__

//DB TCP PACKET
#define DTPK_QUERY									0x0001
#define DTPK_QUERY_PING								0x0002 // DBAgent에서 리턴값 없음.

//SERVER TO MAINSERVER TCP PACKET					0x3501 ~ 0x4000
#define MSTPK_SERVER_INFO							0x3501 
#define MSTPK_CLASS_PRICE_INFO						0x3502
//#define MSTPK_ALL_SERVER_EXIT						0x3503	// 삭제
#define MSTPK_ADMIN									0x3504
#define MSTPK_SERVER_UPDATE							0x3505
#define MSTPK_TOTAL_REG_USER_CNT					0x3506
#define MSTPK_GUILD_CREATE_REG						0x3507
#define MSTPK_GUILD_RANK_LIST						0x3508
#define MSTPK_GUILD_INFO							0x3509
#define MSTPK_GUILD_JOINER_CHANGE					0x3510
#define MSTPK_GUILD_ENTRY_AGREE						0x3511
#define MSTPK_GUILD_LEAVE							0x3512
#define MSTPK_GUILD_TITLE_CHANGE					0x3513
#define MSTPK_GUILD_SIMPLE_INFO						0x3514
#define MSTPK_GUILD_JOIN_USER						0x3515
#define MSTPK_GUILD_MARK_CHANGE						0x3516
#define MSTPK_UPDATE_CLIENT_VERSION					0x3517
#define MSTPK_GUILD_EXIST							0x3518
#define MSTPK_CAMP_DATA_SYNC						0x3519
#define MSTPK_GUILD_MARK_BLOCK_INFO					0x3520
#define MSTPK_LADDER_MODE_RESULT_UPDATE				0x3521
#define MSTPK_GUILD_TITLE_SYNC						0x3522
#define MSTPK_LOAD_CS3_FILE							0x3523
#define MSTPK_LOAD_CS3_FILE_RESULT					0x3524
#define MSTPK_CS3_FILE_VERSION						0x3525
#define MSTPK_CS3_FILE_VERSION_RESULT				0x3526
#define MSTPK_LOW_CONNECT_SERVER_EXIT				0x3527
#define MSTPK_ADD_LADDER_POINT						0x3528
#define MSTPK_CAMP_ROOM_BATTLE_INFO					0x3529
#define MSTPK_CAMP_ENTRY_CHANGE						0x3530
#define MSTPK_CAMP_BATTLE_INFO						0x3531
#define MSTPK_USER_CAMP_POINT_RECORD_INIT			0x3532
#define MSTPK_CAMP_INFLUENCE_ALARM					0x3533
#define MSTPK_AUTO_CLOSE_ANNOUNCE					0x3534 
#define MSTPK_GUILD_NAME_CHANGE						0x3535
#define MSTPK_TRADE_LIST							0x3536
#define MSTPK_TRADE_CREATE_REG						0x3537
#define MSTPK_TRADE_ITEM_TRADE						0x3538
#define MSTPK_TRADE_ITEM_CANCEL						0x3539
#define MSTPK_TRADE_TIME_OUT						0x3540
#define MSTPK_EVENT_SHOP_GOODS_LIST					0x3541
#define MSTPK_EVENT_SHOP_GOODS_BUY					0x3542
#define MSTPK_EVENT_SHOP_STATE						0x3543
#define MSTPK_EVENT_SHOP_BUY_USER_CLEAR				0x3544
#define MSTPK_EVENT_SHOP_GOODS_BUY_RESULT			0x3545 
#define MSTPK_DBAGENT_EXTEND						0x3546
#define MSTPK_GAME_SERVER_RELOAD_INI				0x3547
#define MSTPK_GAME_SERVER_OPTION					0x3548
#define MSTPK_EXTRAITEM_GROWTH_CATALYST_DATA		0x3549
#define MSTPK_EXTRAITEM_GROWTH_MORTMAIN_CHECK		0x3550
#define MSTPK_SERVER_CONNECT						0x3551
#define MSTPK_SERVER_INDEX         					0x3552
#define MSTPK_ALL_SERVER_LIST						0x3553
#define MSTPK_SERVER_PING_CHECK						0x3554 
#define MSTPK_EXTRAITEM_GROWTH_CATALYST_INFO		0x3555	
#define MSTPK_SERVER_INFO_REQ						0x3556
#define MSTPK_SERVER_INFO_ACK						0x3557
#define	MSTPK_GAMESERVER_RELOAD_HACK_CONSTANT		0x3558
#define MSTPK_GAMESERVER_RELOAD_USER_DISPERSION		0x3559
#define MSTPK_GAMESERVER_RELOAD_PROCESS_INI			0x3560
#define MSTPK_GAMESERVER_RELOAD_INI_CLASS			0x3561
#define MSTPK_GAMESERVER_RELOAD_INI_DECO			0x3562
#define MSTPK_GAMESERVER_RELOAD_INI_ETC				0x3563
#define MSTPK_GAMESERVER_RELOAD_INI_EVENT			0x3564
#define MSTPK_GAMESERVER_RELOAD_QUEST_INI			0x3565
#define MSTPK_GAMESERVER_RELOAD_MODE_INI			0x3566
#define MSTPK_GAMESERVER_RELOAD_PRESENT_INI			0x3567
#define MSTPK_GAMESERVER_RELOAD_FISHING_INI			0x3568
#define MSTPK_GAMESERVER_RELOAD_EXCA				0x3569
#define MSTPK_GAMESERVER_RELOAD_ITEM_COMPOUND_INI	0x3570
#define MSTPK_GAMESERVER_RELOAD_EXTRAITEM_INI		0x3571
#define MSTPK_GAMESERVER_RELOAD_TRADE_INI			0x3572
#define MSTPK_GAMESERVER_RELOAD_LEVELMATCH_INI		0x3573
#define MSTPK_GAMESERVER_RELOAD_ITEM_INIT_CONTROL	0x3574
#define MSTPK_GAMESERVER_RELOAD_CONFIG_INI			0x3575
#define MSTPK_GAMESERVER_QUICK_EXIT					0x3576
#define MSTPK_GAMESERVER_SAFETY_EXIT				0x3577
#define MSTPK_GAMESERVER_SETNAGLE_REFCOUNT			0x3578
#define MSTPK_GAMESERVER_SETNAGLE_TIME				0x3579
#define MSTPK_TOURNAMENT_REGULAR_INFO               0x3580 
#define MSTPK_TOURNAMENT_MAIN_INFO					0x3581
#define MSTPK_TOURNAMENT_LIST_REQUEST               0x3582 
#define MSTPK_TOURNAMENT_TEAM_CREATE                0x3583
#define MSTPK_TOURNAMENT_TEAM_INFO                  0x3584
#define MSTPK_TOURNAMENT_TEAM_DELETE				0x3585
#define MSTPK_TOURNAMENT_TEAM_LADDER_POINT_ADD      0x3586
#define MSTPK_TOURNAMENT_SERVER_SYNC                0x3587
#define MSTPK_TOURNAMENT_END_PROCESS                0x3588
#define MSTPK_TOURNAMENT_SCHEDULE_INFO				0x3589
#define MSTPK_TOURNAMENT_TEAM_POSITION_SYNC			0x3590
#define MSTPK_TOURNAMENT_ROUND_TEAM_DATA            0x3591
#define MSTPK_TOURNAMENT_ROUND_START                0x3592
#define MSTPK_TOURNAMENT_ROUND_CREATE_BATTLEROOM    0x3593
#define MSTPK_TOURNAMENT_BATTLEROOM_INVITE          0x3594
#define MSTPK_TOURNAMENT_BATTLE_RESULT              0x3595
#define MSTPK_TOURNAMENT_BATTLE_TEAM_CHANGE         0x3596
#define MSTPK_NODEINFO_REQUEST						0x3597
#define MSTPK_TOURNAMENT_CUSTOM_CREATE              0x3598
#define MSTPK_TOURNAMENT_TEAM_ALLOCATE_LIST			0x3599
#define MSTPK_TOURNAMENT_TEAM_ALLOCATE_DATA			0x3600
#define MSTPK_TOURNAMENT_JOIN_CONFIRM_CHECK			0x3601
#define MSTPK_TOURNAMENT_CONFIRM_REG				0x3602
#define MSTPK_TOURNAMENT_ANNOUNCE_CHANGE			0x3603
#define MSTPK_TOURNAMENT_TOTAL_TEAM_LIST			0x3604
#define MSTPK_TOURNAMENT_CUSTOM_STATE_START			0x3605
#define MSTPK_TOURNAMENT_CUSTOM_REWARD_LIST			0x3606
#define MSTPK_TOURNAMENT_CUSTOM_REWARD_REG_CHECK	0x3607
#define MSTPK_TOURNAMENT_CUSTOM_REWARD_REG_UPDATE	0x3608
#define MSTPK_EVENT_NPC_CLOSE						0x3609
#define MSTPK_EVENT_NPC_CLOSE_REQUEST				0x3610
#define MSTPK_GAMESERVER_CHANGE_RELAYSERVER_STATE   0x3611
#define MSTPK_UPDATE_RELATIVE_GRADE                 0x3612
#define MSTPK_SUPER_GASHPON_LIMIT_CHECK				0x3613
#define MSTPK_SUPER_GASHPON_LIMIT_DECREASE			0x3614
#define MSTPK_SUPER_GASHPON_LIMIT_INFO				0x3615
#define MSTPK_SUPER_GASHPON_LIMIT_RESET				0x3616
#define MSTPK_TOURNAMENT_CHEER_DECISION				0x3617
#define MSTPK_TOURNAMENT_PREV_CHAMP_SYNC            0x3618

//특별상점
#define MSTPK_SPECIAL_SHOP_GOODS_INFO				0x3619
#define MSTPK_SPECIAL_SHOP_GOODS_BUY				0x3620
#define MSTPK_SPECIAL_SHOP_STATE_CHANGE				0x3621
#define MSTPK_SPECIAL_SHOP_GOODS_BUY_RESULT			0x3622
#define MSTPK_GUILD_ENTRY_FAIL						0x3623

//길드 룸
#define MSTPK_REQ_GUILD_ROOM_INDEX					0x3224
#define MSTPK_UPDATE_GUILD_ROOM_INDEX				0x3225
#define MSTPK_DELETE_GUILD_ROOM_INFO				0x3226
#define MSTPK_REQ_ALL_GUILD_ROOM_INFO				0x3227

#define MSTPK_WHITELIST_REQUEST						0x3630

#define MSTPK_TOURNAMENT_MACRO						0x3631

#define MSTPK_MILEAGE_SHOP_GOODS_LIST				0x3640
#define MSTPK_MILEAGE_SHOP_GOODS_BUY				0x3641
#define MSTPK_MILEAGE_SHOP_STATE					0x3642
#define MSTPK_MILEAGE_SHOP_BUY_USER_CLEAR			0x3643
#define MSTPK_MILEAGE_SHOP_GOODS_BUY_RESULT			0x3644
#define MSTPK_REQ_REGIST_COMPENSATION				0x3645

// 거래소 아이템 게임 서버와 싱크
#define MSTPK_TRADE_ITEM_GAMESVR_SYNC				0x3646

#define MSTPK_USER_MATCH_REQUEST					0x3647
#define MSTPK_USER_MATCH_CANCEL						0x3648
#define MSTPK_MATCH_RANKSEASON_SYNC					0x3649

// 일대일모드
#define MSTPK_SUCCESSION_MATCHING_REQUEST			0x3651
#define MSTPK_SUCCESSION_MATCHING_CANCEL			0x3652

// 수련장
#define MSTPC_PRACTICE_INI_LIST						0x3671
#define MSTPC_PRACTICE_INDEXRANK					0x3672
#define MSTPC_PRACTICE_USERUPDATE					0x3673
#define MSTPC_PRACTICE_INIT_DATA					0x3674

#define MSTPK_NICKNAME_CHANGE						0x3680

#define MSTPK_UPDATE_CLIENT_VERSION_RESULT			0x3699

// 해외용 서버 라이센스 체크
#if defined( SRC_OVERSEAS )
#define MSTPK_LICENSE_ALERT_CHECK					0x3700	//게임서버 -> 메인서버
#define	MSTPK_LICENSE_REQUEST						0x3701	
#endif

////////////////////////////////////////////////////////////////////////
enum InternalPacket
{
	ITPK_ACCEPT_SESSION = 0x5555,
	ITPK_CLOSE_SESSION,
	ITPK_FLUSH_PROCESS,
	ITPK_TIMEOUT_TRADE,
	ITPK_QUERY,
	ITPK_SPECIAL_SHOP_CHECK,
	ITPK_TRADE_GAMESVR_SYNC,
	ITPK_MATCH_PROCESS,
	ITPK_MATCH_RANKSEASON,
	ITPK_END
};

//MSTPK_ALL_SERVER_EXIT
#define ALL_SERVER_QUICK_EXIT        0
#define ALL_SERVER_SAFETY_EXIT       1

//MSTPK_LADDER_MODE_RESULT_UPDATE
#define LADDER_TEAM_RESULT_WIN        1
#define LADDER_TEAM_RESULT_LOSE       2
#define LADDER_TEAM_RESULT_TIE        3

//MSTPK_CAMP_INFLUENCE_ALARM                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
#define CAMP_INFLUENCE_ALARM          1
#define CAMP_TODAY_INFLUENCE_ALARM    2

//MSTPK_EXTRAITEM_GROWTH_MORTMAIN_CHECK
#define EXTRAITEM_GROWTH_MORTMAIN_CHECK				1
#define EXTRAITEM_GROWTH_MORTMAIN_COUNT_MINUS   	2
#define EXTRAITEM_GROWTH_MORTMAIN_CHECK_RESULT_OK	10
#define EXTRAITEM_GROWTH_MORTMAIN_CHECK_RESULT_FAIL	11

//MSTPK_TOURNAMENT_TEAM_CREATE
#define MS_TOURNAMENT_TEAM_CREATE_OK             1
#define MS_TOURNAMENT_TEAM_CREATE_APP_END        2
#define MS_TOURNAMENT_TEAM_CREATE_ALREADY_TEAM   3

// MSTPK_SPECIAL_SHOP_GOODS_BUY
#define SPECIAL_SHOP_GOODS_BUY_RESERVE          1       // 물품 예약
#define SPECIAL_SHOP_GOODS_BUY_CLOSE            2       // 상점 종료
#define SPECIAL_SHOP_GOODS_BUY_SOLD_OUT         3       // 재고 없음
#define SPECIAL_SHOP_GOODS_BUY_UNKNOWN          4       // 알수없는 물품
#define SPECIAL_SHOP_GOODS_BUY_LIMIT			5		  // 개인 구매 제한
#define SPECIAL_SHOP_GOODS_BUY_FAILED			6 	  // 서버 이동등의 이유로 실패
#define SPECIAL_SHOP_GOODS_BUY_TERMS_FAILED     7       // 구매 조건이 안됨
#define SPECIAL_SHOP_GOODS_BUY_OK               8       // 구매 완료
#define SPECIAL_SHOP_GOODS_BUY_LIMIT_DATE       9       // 기간 제한으로 판매 종료

// MSTPK_EVENT_SHOP_GOODS_BUY_RESULT
#define SPECIAL_SHOP_GOODS_BUY_RESULT_OK      1   // 물품 구매 완료
#define SPECIAL_SHOP_GOODS_BUY_RESULT_CANCEL   2   // 물품 구매 취소

//CLIENT SEND TCP MONITORING PACKET
#define CTPKM_REQUEST_NUM_CONNECT					0x8001
#define CTPKM_ANNOUNCE								0x8002
#define CTPKM_UPDATE_CLIENT_VERSION					0x8003
#define CTPKM_LOAD_CS3_FILE							0x8004
#define CTPKM_MONITOR_IP							0x8005
#define CTPKM_CS3_FILE_VERSION						0x8006
#define CTPKM_SERVER_INFO_REQUEST					0x8007
#define CTPKM_MAINSERVER_EXIT						0x8008
#define CTPKM_MAINSERVER_QUICKALLEXIT				0x8009
#define CTPKM_MAINSERVER_SAFETYALLEXIT				0x8010
#define CTPKM_MAINSERVER_RELOADCLOSEINFO			0x8011
#define	CTPKM_MAINSERVER_DBAGENT_EXTEND				0x8012
#define CTPKM_MAINSERVER_GAMESERVER_OPTION			0x8013
#define CTPKM_MAINSERVER_GAMESERVER_RELOADINI		0x8014
#define CTPKM_MAINSERVER_EXTRAITEM_INI				0x8015
#define CTPKM_MAINSERVER_EVENTSHOP_INI				0x8016
#define CTPKM_GAMESERVER_PROTOCAL					0x8017
#define	CTPKM_GAMESERVER_RELOAD_HACK_CONSTANT		0x8018
#define CTPKM_GAMESERVER_RELOAD_USER_DISPERSION		0x8019
#define CTPKM_GAMESERVER_RELOAD_PROCESS_INI			0x8020
#define CTPKM_GAMESERVER_RELOAD_INI_CLASS			0x8021
#define CTPKM_GAMESERVER_RELOAD_INI_DECO			0x8022
#define CTPKM_GAMESERVER_RELOAD_INI_ETC				0x8023
#define CTPKM_GAMESERVER_RELOAD_INI_EVENT			0x8024
#define CTPKM_GAMESERVER_RELOAD_QUEST_INI			0x8025
#define CTPKM_GAMESERVER_RELOAD_MODE_INI			0x8026
#define CTPKM_GAMESERVER_RELOAD_PRESENT_INI			0x8027
#define CTPKM_GAMESERVER_RELOAD_FISHING_INI			0x8028
#define CTPKM_GAMESERVER_RELOAD_EXCA				0x8029
#define CTPKM_GAMESERVER_RELOAD_ITEM_COMPOUND_INI	0x8030
#define CTPKM_GAMESERVER_RELOAD_EXTRAITEM_INI		0x8031
#define CTPKM_GAMESERVER_RELOAD_TRADE_INI			0x8032
#define CTPKM_GAMESERVER_RELOAD_LEVELMATCH_INI		0x8033
#define CTPKM_GAMESERVER_RELOAD_ITEM_INIT_CONTROL	0x8034
#define CTPKM_GAMESERVER_RELOAD_CONFIG_INI			0x8035
#define CTPKM_GAMESERVER_QUICK_EXIT					0x8036
#define CTPKM_GAMESERVER_SAFETY_EXIT				0x8037
#define	CTPKM_MAINSERVER_GS_SETNAGLE_REFCOUNT		0x8038
#define CTPKM_MAINSERVER_GS_SETNAGLE_TIME			0x8039
#define CTPKM_MAINSERVER_ADMINCOMMAND				0x8040
#define CTPKM_GAMESERVER_CHANGE_RELAYSVR_STATE      0x8041
#define CTPKM_MAINSERVER_RESETEVENTSHOP				0x8042
#define CTPKM_WHITELIST_REQUEST						0X8048
#define CTPKM_MAINSERVER_RESETBINGONUMBER			0X8050
#define CTPKM_MAINSERVER_RESET_OLDMISSIONDATA		0x8051

// 해외용 서버 라이센스 체크
#if defined( SRC_OVERSEAS )
#define CTPKM_LICENSE_REQUEST						0X8047
#endif

#define CTPKM_MTOOL_GAMESERVER_PROTOCAL				0x8201
#define CTPKM_MTOOL_MAINSERVER_EXIT					0x8202
#define CTPKM_MTOOL_MAINSERVER_QUICKALLEXIT			0x8204
#define CTPKM_MTOOL_MAINSERVER_SAFETYALLEXIT		0x8207
#define CTPKM_MTOOL_MAINSERVER_GAMESERVER_RELOADINI	0x8210
#define CTPKM_MTOOL_MAINSERVER_RELOADCLOSEINFO		0x8213

//SERVER SEND TCP MONITORING PACKET
#define STPKM_ANSWER_NUM_CONNECT					0x8501
#define STPKM_SERVER_DISCONNECT						0x8502
#define STPKM_LOAD_CS3_FILE							0x8503
#define STPKM_CS3_FILE_VERSION						0x8504
#define STPKM_ALL_SERVER_INFO						0x8505
#define STPKM_SERVER_INFO_ACK						0x8506
#define STPKM_ADMIN_RESPONSE						0x8507
#define STPKM_UPDATE_CLIENT_VERSION					0x8516

// 해외용 서버 라이센스 체크
#if defined( SRC_OVERSEAS )
#define STPKM_LICENSE_ALERT_CHECK					0x8513	// 메인서버 -> 모니터링 툴 
#endif

// CTPKM_ANNOUNCE
#define ANNOUNCE_TYPE_ALL        1
#define ANNOUNCE_TYPE_ONE        2
#define ANNOUNCE_TYPE_DISCONNECT 3

// STPKM_LOAD_CS3_FILE , MSTPK_LOAD_CS3_FILE_RESULT
#define LOAD_CS3_FILE_SUCCESS          1
#define LOAD_CS3_FILE_FAIL             2
#define LOAD_CS3_FILE_WRONG_VERSION    3
#define LOAD_CS3_FILE_NOT_FILE         4
#define LOAD_CS3_FILE_CHANGE_WRONG     5
#define LOAD_CS3_FILE_EXIST_VERSION    6


// MSTPK_TRADE_ITEM_TRADE
#define TRADE_ITEM_GET_INFO		1
#define TRADE_ITEM_TRADE_FAIL	2
#define TRADE_ITEM_TRADE_OK		3
#define TRADE_ITEM_NO_ITEM		4
#define TRADE_ITEM_PESO			5
#define TRADE_ITEM_DEL			6
#define TRADE_ITEM_OWNER		7


// MSTPK_TRADE_ITEM_CANCEL
#define TRADE_ITEM_CANCEL_GET_INFO	1
#define TRADE_ITEM_CANCEL_FAIL		2
#define TRADE_ITEM_CANCEL_OK		3
#define TRADE_ITEM_CANCEL_NO_ITEM	4
#define TRADE_ITEM_CANCEL_NOT_OWNER	5
#define TRADE_ITEM_CANCEL_DEL		6

// MSTPK_EVENT_SHOP_GOODS_BUY
#define EVENT_SHOP_GOODS_BUY_RESERVE          1       // 물품 예약
#define EVENT_SHOP_GOODS_BUY_CLOSE            2       // 상점 종료
#define EVENT_SHOP_GOODS_BUY_SOLD_OUT         3       // 재고 없음
#define EVENT_SHOP_GOODS_BUY_UNKNOWN          4       // 알수없는 물품
#define EVENT_SHOP_GOODS_BUY_LIMIT			  5		  // 개인 구매 제한
#define EVENT_SHOP_GOODS_BUY_FAILED			  6 	  // 서버 이동등의 이유로 실패
#define EVENT_SHOP_GOODS_BUY_TERMS_FAILED     7       // 구매 조건이 안됨
#define EVENT_SHOP_GOODS_BUY_OK               8       // 구매 완료
#define EVENT_SHOP_GOODS_BUY_LIMIT_DATE       9       // 기간 제한으로 판매 종료

// MSTPK_EVENT_SHOP_GOODS_BUY_RESULT
#define EVENT_SHOP_GOODS_BUY_RESULT_OK      1   // 물품 구매 완료
#define EVENT_SHOP_GOODS_BUY_RESULT_CANCEL  2   // 물품 구매 취소

// MSTPK_TOURNAMENT_TEAM_ALLOCATE_DATA 
#define TOURNAMENT_TEAM_ALLOCATE_OK         1
#define TOURNAMENT_TEAM_ALLOCATE_END        2 

// MSTPK_TOURNAMENT_JOIN_CONFIRM_CHECK
#define TOURNAMENT_JOIN_CONFIRM_OK          1
#define TOURNAMENT_JOIN_CONFIRM_CLOSE       2
#define TOURNAMENT_JOIN_CONFIRM_FAILED      3

// MSTPK_TOURNAMENT_ANNOUNCE_CHANGE
#define TOURNAMENT_ANNOUNCE_CHANGE_OK       1
#define TOURNAMENT_ANNOUNCE_CHANGE_CLOSE    2
#define TOURNAMENT_ANNOUNCE_CHANGE_FAILED   3

// MSTPK_TOURNAMENT_CUSTOM_STATE_START
#define TOURNAMENT_CUSTOM_STATE_START_OK		1
#define TOURNAMENT_CUSTOM_STATE_START_CLOSE		2
#define TOURNAMENT_CUSTOM_STATE_START_FAILED	3

// MSTPK_TOURNAMENT_CUSTOM_REWARD_REG_CHECK
#define TOURNAMENT_CUSTOM_REWARD_REG_CHECK_OK   1
#define TOURNAMENT_CUSTOM_REWARD_REG_CLOSE      2
#define TOURNAMENT_CUSTOM_REWARD_REG_EMPTY_SLOT 3
#define TOURNAMENT_CUSTOM_REWARD_REG_NOT_OWNER  4

// MSTPK_GUILD_ENTRY_AGREE
const int GUILD_ENTRY_POSSIBLE		=			1;  // 길드 가입 가능
const int GUILD_ENTRY_IMPOSSIBEL	=			2;	// 길드 가입 불가능

// 매칭 유저 수 
#define MAX_MATCHING_COUNT						2

// 관리자명령어 정리
enum AdminCommandTypes
{
	ADMINCOMMAND_NONE = 0,
	ADMINCOMMAND_KICK,
	ADMINCOMMAND_ANNOUNCE,
	ADMINCOMMAND_ITEMINSERT,
	ADMINCOMMAND_EVENTINSERT,
	ADMINCOMMAND_AUTH,
	ADMINCOMMAND_USERBLOCK,
	ADMINCOMMAND_USERUNBLOCK,
	ADMINCOMMAND_SECRETSHOP,
	ADMINCOMMAND_COMPENSATION,
	ADMINCOMMAND_PRACTICE,

	ADMINCOMMAND_MTOOL_AUTH,
	ADMINCOMMAND_MTOOL_KICK,
	ADMINCOMMAND_MTOOL_ANNOUNCE,
	ADMINCOMMAND_MTOOL_ITEMINSERT,
	ADMINCOMMAND_MTOOL_EVENTINSERT,
	ADMINCOMMAND_MTOOL_USERBLOCK,
	ADMINCOMMAND_MTOOL_USERUNBLOCK,
	ADMINCOMMAND_MTOOL_SECRETSHOP,
	ADMINCOMMAND_MTOOL_COMPENSATION,
	ADMINCOMMAND_MTOOL_PRACTICE,

	ADMINCOMMAND_END
};

enum AdminLevels
{
	ADMIN_LEVEL_NONE = 0,
	ADMIN_LEVEL_OPERATOR,
	ADMIN_LEVEL_ADMINISTRATOR,
	ADMIN_LEVEL_DEVELOPER,
	ADMIN_LEVEL_END
};

// MSTPK_SUPER_GASHPON_LIMIT_CHECK
enum
{
	SUPER_GASHPON_LIMIT_REMAIN,
	SUPER_GASHPON_LIMIT_FULL,
	SUPER_GASHPON_LIMIT_INFO_GET,
};

enum
{
	TOURNAMENT_CHEER_DECISION_OK		     = 1,
	TOURNAMENT_CHEER_DECISION_ALREADY	     = 2,
	TOURNAMENT_CHEER_DECISION_NONE_TEAM      = 3,
	TOURNAMENT_CHEER_DECISION_CLOSE		     = 4,
	TOURNAMENT_CHEER_DECISION_NOT_REGULAR    = 5,		
	TOURNAMENT_CHEER_DECISION_NOT_TEAM_DELAY = 6,
	TOURNAMENT_CHEER_DECISION_FAIL		     = 7,
};

//MSTPK_REQ_GUILD_ROOM_INDEX
enum
{
	GUILD_ROOM_CREATE	= 1,
	GUILD_ROOM_WAIT		= 2,
	GUILD_ROOM_INFO		= 3,
};

//상태 정의

enum TournamentMacro
{
	TM_NEXT_STATE	= 0,
	TM_RESULT		= 1,
	TM_END			= 2,
};

enum
{
	MATCH_SUCCESS	= 1,
	MATCH_FAILED	= 2,
	MATCH_TIMEOVER	= 3,
};

enum
{
	RELOAD_HACK = 0,
	RELOAD_USERDISPERSION,
    RELOAD_PROCESS,
	RELOAD_CLASS,
	RELOAD_DECO,
	RELOAD_ETC,
	RELOAD_EVENT,
	RELOAD_QUEST,
	RELOAD_MODE,
	RELOAD_PRESENT,
	RELOAD_EXCAVATION,
	RELOAD_FISHING,
	RELOAD_ITEMCOMPOUND,
	RELOAD_EXTRAITEM,
	RELOAD_TRADE,
	RELOAD_LEVELMATCH,
	RELOAD_ITEMINIT_CONTROL,
	RELOAD_CONFIG,
	RELOAD_ALCHEMIC_MGR,
	RELOAD_PET,
	RELOAD_AWAKE,
	RELOAD_MISSION,
	RELOAD_ROLLBOOK,
	RELOAD_COSTUMESHOP,
	RELOAD_COSTUME,
	RELOAD_MEDAL,
	RELOAD_SETITEM,
	RELOAD_SUPERGASHAPON,
	RELOAD_ACCESSORY,
	RELOAD_RANKING,
	RELOAD_SUCCESSION_MODE,
	RELOAD_TIMEGATE,
};

enum
{
	PRACTICE_RESULT_SUCCESS		= 0,
	PRACTICE_RESULT_FAIL		= 1,
	PRACTICE_RESULT_ADDICTION	= 2,
	PRACTICE_RESULT_TIME_SHORT	= 3,
};

#endif
